name: Docker Image CI

on:
  push:
    branches: ["main"]
env:
  # 设置 docker 镜像名
  IMAGE_NAME: ghcr.io/ittoyxk/freeswitch
jobs:

  push-store-image:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v3

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}


      - name: Build and push image
        run:
          |
          docker pull ghcr.io/ittoyxk/freeswitch:latest
          docker tag ghcr.io/ittoyxk/freeswitch:latest registry.cn-beijing.aliyuncs.com/ittoyxk/freeswitch:latest
          docker login --username=hxk_xiaokang@163.com -password=XiaoKang000 registry.cn-beijing.aliyuncs.com
          docker push registry.cn-beijing.aliyuncs.com/ittoyxk/freeswitch:latest
