name: Docker Image CI

on:
  push:
    branches: ["main"]
    tags: "*"
env:
  # 设置 docker 镜像名
  IMAGE_NAME: ghcr.io/ittoyxk/freeswitch
jobs:

  push-store-image:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v3

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}


      - name: Build and push image
        run:
          |
          # 从 GitHub.ref 中取出版本
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          # 从 tag 名字中替换 v 字符
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION)
          # Use Docker `latest` tag convention
          [ "$VERSION" == "main" ] && VERSION=latest
          echo VERSION=$VERSION
          docker build . --file Dockerfile --tag $IMAGE_NAME:$VERSION
          docker push $IMAGE_NAME:$VERSION
          docker tag $IMAGE_NAME:$VERSION registry.cn-beijing.aliyuncs.com/ittoyxk/freeswitch:$VERSION
          docker login --username=${{secrets.ALIYUN_USERNAME}} --password=${{secrets.ALIYUN_PASSWORD}} registry.cn-beijing.aliyuncs.com
          docker push registry.cn-beijing.aliyuncs.com/ittoyxk/freeswitch:$VERSION
